image: docker/compose:1.29.2

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

  PROJECT_VERSION: $CI_COMMIT_REF_NAME
  PROJECT_REGISTRY_REPO: $CI_REGISTRY_IMAGE
  
workflow:
  rules:
    # development
    - if: &develop $CI_COMMIT_BRANCH == 'develop'
      variables:
        COMPOSE_PROJECT_NAME: $CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-development
        PROJECT_NAME: $CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-development
        PROJECT_ENV: development
        PROJECT_DOMAIN: dev.montetuning.com

    # production
    - if: &production $CI_COMMIT_TAG =~ /v.+/
      variables:
        COMPOSE_PROJECT_NAME: $CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-production
        PROJECT_NAME: $CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-production
        PROJECT_ENV: production
        PROJECT_DOMAIN: montetuning.com

build:
  stage: build
  variables:
    COMPOSE_DOCKER_CLI_BUILD: 1
    DOCKER_BUILDKIT: 1
  services:
    - docker:dind
  script:
    - docker-compose build
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker-compose push

deploy:
  image: alpine:latest
  stage: deploy
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker ps -a"
    - scp -i $ID_RSA docker-compose.yml $SERVER_USER@$SERVER_IP:/home/$SERVER_USER
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME PROJECT_REGISTRY_REPO=$PROJECT_REGISTRY_REPO PROJECT_VERSION=$PROJECT_VERSION PROJECT_NAME=$PROJECT_NAME PROJECT_DOMAIN=$PROJECT_DOMAIN docker-compose pull"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME PROJECT_REGISTRY_REPO=$PROJECT_REGISTRY_REPO PROJECT_VERSION=$PROJECT_VERSION PROJECT_NAME=$PROJECT_NAME PROJECT_DOMAIN=$PROJECT_DOMAIN docker-compose up -d --remove-orphans"
  environment:
    name: $PROJECT_ENV
    url: $PROJECT_DOMAIN