export { default as toggleBodyNavShowed } from './toggleBodyNavShowed'
export { default as getScrollbarSize } from './getScrollbarSize'
export { default as toggleBodyScroll } from './toggleBodyScroll'
export { default as getBaseUrl } from './getBaseUrl'
export { default as getHrefWithLocale } from './getHrefWithLocale'
export { default as getRandomId } from './getRandomId'
export { default as getCarPowerGain } from './getCarPowerGain'
export { default as numberFormat } from './numberFormat'
export { default as getSwiperActiveSlideEl } from './getSwiperActiveSlideEl'
export { default as getSwiperSlideIndexById } from './getSwiperSlideIndexById'
export { default as getHrefFromTelStr } from './getHrefFromTelStr'
export { default as sleep } from './sleep'
export { getProductById } from './getProductById'
export { getProductDataById } from './getProductDataById'
export { getTotalPriceOfProductsInCart } from './getTotalPriceOfProductsInCart'
export { getTotalPriceWithDiscountOfProductsInCart } from './getTotalPriceWithDiscountOfProductsInCart'
export { getTotalDiscountSumForProductsInCart } from './getTotalDiscountSumForProductsInCart'
export { mapProductsFromApi } from './mapProductsFromApi'
export * from './getClassNameModificators'
export type { productIds, Product, ProductId } from '../types/product'
export {
  default as initLazyLoad,
  getLazyLoadInstance,
  getLazyLoadSelector,
} from './vanilla-lazyload'
